steps:
      - name: 拉取你的代码
        uses: actions/checkout@v4

      - name: 安装基础依赖环境
        run: |
          brew install ldid xz

      - name: 安装 Theos 和 iOS SDK
        run: |
          export THEOS=~/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mv sdks-master/* $THEOS/sdks/
          rm -rf master.zip sdks-master

      # 👇 新增：在编译前自动下载 fishhook
      - name: 下载 Fishhook
        run: |
          curl -O https://raw.githubusercontent.com/facebook/fishhook/master/fishhook.h
          curl -O https://raw.githubusercontent.com/facebook/fishhook/master/fishhook.c

      - name: 开始编译 Dylib
        run: |
          export THEOS=~/theos
          make

      - name: 打包并上传
        uses: actions/upload-artifact@v4
        with:
          name: Hook-Dylib
          path: .theos/obj/debug/*.dylib
