name: Compile iOS Dylib

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # 允许手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取你的代码
        uses: actions/checkout@v3

      - name: 安装基础依赖环境
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential fakeroot git perl python3 unzip curl

      - name: 安装 Theos 和 iOS SDK
        run: |
          export THEOS=~/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mv sdks-master/* $THEOS/sdks/
          rm -rf master.zip sdks-master

      - name: 开始编译 Dylib
        run: |
          export THEOS=~/theos
          make

      - name: 打包并上传生成的 Dylib 供下载
        uses: actions/upload-artifact@v3
        with:
          name: Hook-Dylib
          path: .theos/obj/debug/*.dylib
