name: Compile iOS Dylib

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: macos-latest  # <-- 核心修改：直接换成苹果 Mac 服务器！

    steps:
      - name: 拉取你的代码
        uses: actions/checkout@v4

      - name: 安装基础依赖环境 (macOS 环境)
        run: |
          brew install ldid xz

      - name: 安装 Theos 和 iOS SDK
        run: |
          export THEOS=~/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mv sdks-master/* $THEOS/sdks/
          rm -rf master.zip sdks-master

      - name: 开始编译 Dylib
        run: |
          export THEOS=~/theos
          make

      - name: 打包并上传生成的 Dylib 供下载
        uses: actions/upload-artifact@v4
        with:
          name: Hook-Dylib
          path: .theos/obj/debug/*.dylib
